version: '3'
services:
  frontend-service:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://backend-service:8080
    ports:
      - "3000:80"
    depends_on:
      - backend-service
    networks:
      - app-network
    container_name: backend-service

  backend-service:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db-service
    networks:
      - app-network

  db-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
