version: '3'
services:
  frontend-service:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-service

  backend-service:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db-service

  db-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
