apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: sample-app
spec:
  capacity:
    storage: 5Gi # Define the storage size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/mongo-pv # This path should exist on the node
