apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-logs
  namespace: sample-app
  labels:
    k8s-app: fluentd-logs
spec:
  selector:
    matchLabels:
      name: fluentd-logs
  template:
    metadata:
      labels:
        name: fluentd-logs
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.17.1-debian-1.0
        env:
        - name: FLUENTD_ARGS
          value: "--no-supervisor -q"
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers     # Path where logs are stored in Kubernetes
        - name: persistent-storage
          mountPath: /fluentd/logs           # Persistent storage for logs
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers           # Host path where Kubernetes stores logs
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: log-pvc  