apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  namespace: sample-app
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/jackson/data/fluentd-logs
