apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: jacksonlobo/app-frontend:1.0.0
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config   # Reference to the ConfigMap
              key: REACT_APP_BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 80            
      targetPort: 80       
      nodePort: 30001     
  selector:
    app: frontend

